### ISSUE TITLE
Invalid `content_warnings` in `.cdb.json`

### ISSUE THREAD

**Issue by rubenwardy** [minetest-palamod/palamod#12]
Hi,

The ContentDB release creation is failing because of an invalid value given to `content_warnings`:

https://github.com/minetest-palamod/palamod/blob/master/.cdb.json#L7

This should be removed completely, or it should be `"content_warnings": []`.

`content_warning` is not a nullable value, as it is a list.

I've created an issue on ContentDB to make this error more graceful: https://github.com/minetest/contentdb/issues/298

**Comment by AFCMS** [comment]
FIxed! Thanks @rubenwardy !
