### ISSUE TITLE
Build Instructions?

### ISSUE THREAD

**Issue by MoustacheOff** [minetest-palamod/palamod#24]
**Is your feature request related to a problem? Please describe.**
Yes. There is no instructions for how to build and use the mods.

**Describe the solution you'd like**
Update README.md

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MoustacheOff** [comment]
Thanks!

**Comment by AFCMS** [comment]
Fixed by 5e90160fccdbcd9ddbf73989a81c0a344a9043c8
